### ISSUE TITLE
SSH service not restarting

### ISSUE THREAD

**Issue by 00dav00** [stackbuilders/sb-debian-base#92]
After running the `bootstrap` task the expected behavior if that the `root` user can't login using ssh, but this is not happening.

There seems to be a [bug in the handler](https://github.com/stackbuilders/sb-debian-base/blob/master/handlers/main.yml#L4), instead of `sshd` it is using `ssh` as the name of the service, which is causing the deamon not to be restarted.

**Comment by goetzc** [comment]
As I mentioned on the PR, the actual service is called `ssh` and sshd is just an alias, so this should not be the cause for the error you are seeing (will try to reproduce later). We have to remember that handlers are called at the end of the playbook execution. The bug could be that maybe the handler is not being called at all?

**Comment by 00dav00** [comment]
Let's try to reproduce it later, I will have vagrant machine ready for this. The handler is called but does not trigger the service restart.

**Comment by goetzc** [comment]
On which OS do you see this behavior?

**Comment by goetzc** [comment]
I can not reproduce this. If the playbook runs without errors, the handlers are called and the service is restarted, which can be confirmed using `systemctl status ssh` and checking the "Active" time. The second time the playbook is run, as the config file is not changed, the handlers are not called, which is the expected behavior. Also if the playbook ends with an error, the handlers are not called. 

I suppose the playbook you run is failing preventing the handlers from running, please confirm if this is the case. Anyway, we can change this so that the handler is called immediately after running the last _sshd_config_ related task using `- meta: flush_handlers`.

**Comment by 00dav00** [comment]
You are right @goetzc, I reproduced the error with the following execution order:
```
Execution 1:
 - Disallow SSH password authentication (Run correctly, marked as changed)
 - Disallow root SSH access (Run correctly, marked as changed)
 - Make sure a task following the 2 previous ones fails
 - The handler is not executed (Skipped because of failure on playbook task)

Execution 2:
 - Disallow SSH password authentication (Skipped, marked as not changed)
 - Disallow root SSH access (Skipped, marked as not changed)
 - All following tasks run correctly
 - The handler is not executed (Skipped because SSH related tasks are marked as not making changes)
```

So as you said the service name is the handler is not the problem, but the handler itself not executing. I will try `- meta: flush_handlers` as suggested
